"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class InternalServerErrorEnum(str, Enum):
    r"""Something went wrong"""
    INTERNAL_SERVER_ERROR = 'Internal Server Error'
