"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from hightouch import utils
from typing import Any, Final


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class ValidateErrorJSON:
    details: dict[str, Any] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('details') }})
    MESSAGE: Final[str] = dataclasses.field(default='Validation failed', metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('message') }})
    

