"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.errors import validateerrorjson as errors_validateerrorjson
from ...models.shared import internalservererror as shared_internalservererror
from ...models.shared import model as shared_model
from ...models.shared import modelcreate as shared_modelcreate
from typing import Optional, Union


@dataclasses.dataclass
class CreateModelRequest:
    model_create: shared_modelcreate.ModelCreate = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    skip_column_query: Optional[bool] = dataclasses.field(default=False, metadata={'query_param': { 'field_name': 'skipColumnQuery', 'style': 'form', 'explode': True }})
    



@dataclasses.dataclass
class CreateModelResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    one_of: Optional[Union[shared_model.Model, errors_validateerrorjson.ValidateErrorJSON, shared_internalservererror.InternalServerError]] = dataclasses.field(default=None)
    r"""Ok"""
    

