"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.shared import syncsequencestatusoutput as shared_syncsequencestatusoutput
from typing import Optional


@dataclasses.dataclass
class GetSyncSequenceRunRequest:
    sync_sequence_run_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'syncSequenceRunId', 'style': 'simple', 'explode': False }})
    r"""The id of the sync sequence run"""
    



@dataclasses.dataclass
class GetSyncSequenceRunResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    sync_sequence_status_output: Optional[shared_syncsequencestatusoutput.SyncSequenceStatusOutput] = dataclasses.field(default=None)
    r"""Ok"""
    

