"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import triggerrunidgraphinput as shared_triggerrunidgraphinput
from typing import Any, Optional



@dataclasses.dataclass
class TriggerRunIDGraphRequest:
    graph_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'graphId', 'style': 'simple', 'explode': False }})
    trigger_run_id_graph_input: Optional[shared_triggerrunidgraphinput.TriggerRunIDGraphInput] = dataclasses.field(default=None, metadata={'request': { 'media_type': 'application/json' }})
    




@dataclasses.dataclass
class TriggerRunIDGraphResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    r"""Raw HTTP response; suitable for custom response parsing"""
    trigger_run_id_graph_output: Optional[dict[str, Any]] = dataclasses.field(default=None)
    r"""Ok"""
    validate_error_json: Optional[dict[str, Any]] = dataclasses.field(default=None)
    r"""Validation Failed"""
    

