"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import triggersequencerunoutput as shared_triggersequencerunoutput
from ..shared import validateerrorjson as shared_validateerrorjson
from typing import Optional


@dataclasses.dataclass
class TriggerSequenceRunRequest:
    sync_sequence_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'syncSequenceId', 'style': 'simple', 'explode': False }})
    r"""The id of the sync sequence to trigger a run"""
    



@dataclasses.dataclass
class TriggerSequenceRunResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    r"""Raw HTTP response; suitable for custom response parsing"""
    trigger_sequence_run_output: Optional[shared_triggersequencerunoutput.TriggerSequenceRunOutput] = dataclasses.field(default=None)
    r"""Ok"""
    validate_error_json: Optional[shared_validateerrorjson.ValidateErrorJSON] = dataclasses.field(default=None)
    r"""Validation Failed"""
    

