"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import triggerrunidgraphinput as shared_triggerrunidgraphinput
from ..shared import triggerrunidgraphoutput as shared_triggerrunidgraphoutput
from ..shared import validateerrorjson as shared_validateerrorjson
from typing import Optional



@dataclasses.dataclass
class TriggerRunIDGraphRequest:
    graph_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'graphId', 'style': 'simple', 'explode': False }})
    trigger_run_id_graph_input: Optional[shared_triggerrunidgraphinput.TriggerRunIDGraphInput] = dataclasses.field(default=None, metadata={'request': { 'media_type': 'application/json' }})
    




@dataclasses.dataclass
class TriggerRunIDGraphResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    trigger_run_id_graph_output: Optional[shared_triggerrunidgraphoutput.TriggerRunIDGraphOutput] = dataclasses.field(default=None)
    r"""Ok"""
    validate_error_json: Optional[shared_validateerrorjson.ValidateErrorJSON] = dataclasses.field(default=None)
    r"""Validation Failed"""
    

