"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.errors import validateerrorjson as errors_validateerrorjson
from ...models.shared import internalservererror as shared_internalservererror
from ...models.shared import sync as shared_sync
from ...models.shared import syncupdate as shared_syncupdate
from typing import Optional, Union


@dataclasses.dataclass
class UpdateSyncRequest:
    sync_update: shared_syncupdate.SyncUpdate = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    sync_id: float = dataclasses.field(metadata={'path_param': { 'field_name': 'syncId', 'style': 'simple', 'explode': False }})
    r"""The sync's ID"""
    



@dataclasses.dataclass
class UpdateSyncResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    one_of: Optional[Union[shared_sync.Sync, errors_validateerrorjson.ValidateErrorJSON, shared_internalservererror.InternalServerError]] = dataclasses.field(default=None)
    r"""Ok"""
    

